# Generated by Django 4.1 on 2022-08-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='institucion',
            field=models.CharField(max_length=50),
        ),
    ]
